# Generated by Django 5.2.5 on 2025-08-27 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سالن')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('opening_time', models.TimeField(default='09:00', verbose_name='ساعت شروع')),
                ('closing_time', models.TimeField(default='21:00', verbose_name='ساعت پایان')),
                ('closed_days', models.CharField(default='friday', help_text='روزهای تعطیل (جمعه کاما-separated)', max_length=20, verbose_name='روزهای تعطیل')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.TextField(blank=True, help_text='تخصص\u200cها (مثال: ژل\u200cلاک، کاشت)')),
                ('is_available', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salons.salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
