# Generated by Django 5.2.5 on 2025-08-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'سالن', 'verbose_name_plural': 'سالن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'کارمند', 'verbose_name_plural': 'کارمندان'},
        ),
        migrations.AlterField(
            model_name='salon',
            name='closed_days',
            field=models.CharField(blank=True, help_text='روزهای تعطیل را با کاما جدا کنید (مثال: friday,saturday)', max_length=100, verbose_name='روزهای تعطیل'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'salon_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='در دسترس'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialties',
            field=models.TextField(blank=True, help_text='تخصص\u200cها (مثال: ژل\u200cلاک، کاشت، پدیکور)', verbose_name='تخصص\u200cها'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
