# Generated by Django 5.2.5 on 2025-08-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
            ],
        ),
    ]
