# Generated by Django 5.2.5 on 2025-08-27 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15, message='مدت زمان باید حداقل 15 دقیقه باشد')], verbose_name='مدت زمان (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000, message='قیمت باید حداقل 1000 تومان باشد')], verbose_name='قیمت (تومان)'),
        ),
    ]
